TheAccessSystemCourseWork/Controllers/RightsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using TheAccessSystemCourseWork.Models;
using TheAccessSystemCourseWork.Repositories.Interfaces;

namespace TheAccessSystemCourseWork.Controllers
{
    [ApiController]
    [Route("[controller]")]
    //[Authorize(Roles = "Admin")]
    public class RightsController : Controller
    {
        private readonly IRightsLevelRepository _rightsLevelRepository;

        public RightsController(IRightsLevelRepository rightsLevelRepository)
        {
            _rightsLevelRepository = rightsLevelRepository;
        }

        [HttpGet("List")]
        public async Task<IActionResult> List()
        {
            try
            {
                var rightsList = await _rightsLevelRepository.FindRightsLevelsAsync();
                return View(rightsList);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        [HttpGet("Create")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost("Create")]
        public async Task<IActionResult> CreateRights([FromForm] RightsLevel rightsLevel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var success = await _rightsLevelRepository.AddRightsLevelAsync(rightsLevel);
                if (success)
                {
                    return RedirectToAction("List");
                }

                return StatusCode(500, "An error occurred while creating the rights level.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }


        [HttpGet("Update/{id}")]
        public async Task<IActionResult> Update(string id)
        {
            try
            {
                var rightsLevel = await _rightsLevelRepository.GetRightsLevelByIdAsync(id);
                if (rightsLevel == null)
                {
                    return NotFound($"Права с идентификатором {id} не найдены.");
                }

                return View(rightsLevel);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }

        [HttpPost("Update")]
        public async Task<IActionResult> UpdateRights([FromForm] RightsLevel rightsLevel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            try
            {
                var success = await _rightsLevelRepository.UpdateRightsLevelAsync(rightsLevel);
                if (success)
                {
                    return RedirectToAction("List");
                }

                return NotFound($"Права с идентификатором {rightsLevel.ID} не найдены.");
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Internal server error: {ex.Message}");
            }
        }
    }
}

TheAccessSystemCourseWork/Controllers/UserController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheAccessSystemCourseWork.Models;
using TheAccessSystemCourseWork.Repositories.Interfaces;
using TheAccessSystemCourseWork.Services;

namespace TheAccessSystemCourseWork.Controllers;

[ApiController]
[Route("{controller}")]
public class UserController : Controller
{
    private readonly IUserRepository _userRepository;
    private readonly IPassRepository _passRepository;
    private readonly IGuestRepository _guestRepository;
    private readonly IEmployeeRepository _employeeRepository;
    private readonly AuthService _authService;

    public UserController(IUserRepository userRepository, 
                          IPassRepository passRepository,
                          IGuestRepository guestRepository,
                          IEmployeeRepository employeeRepository,
                          AuthService authService)
    {
        _userRepository = userRepository;
        _passRepository = passRepository;
        _guestRepository = guestRepository;
        _employeeRepository = employeeRepository;
        _authService = authService;
    }
    
    [Route("Login")]
    [HttpGet]
    public IActionResult Login()
    {
        return View();
    }
    
    [Route("Login")]
    [HttpPost]
    public async Task<IActionResult> Login([FromForm]string login, [FromForm]string password)
    {
        if (!await _authService.ValidateUserCredentials(login, password))
        {
            ModelState.AddModelError(string.Empty, "Invalid login or password.");
            return View();
        }

        var user = await _userRepository.GetUserByLoginAsync(login);

        await _authService.SignInUser(HttpContext, user);

        return RedirectToAction("PersonalAccount");
    }
    
    [Route("PersonalAccount")]
    [HttpGet]
    public async Task<IActionResult> PersonalAccount()
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
        if (userId == null)
        {
            return Unauthorized();
        }

        var user = await _userRepository.GetUserByIdAsync(Guid.Parse(userId));
        if (user == null)
        {
            return NotFound("User not found.");
        }

        if (User.IsInRole("Guest"))
        {
            var guest = await _guestRepository.GetGuestByUserIDAsync(user.ID);
            if (guest == null)
            {
                return NotFound("Информация о госте не найдена.");
            }
            var viewModel = new PersonalAccountViewModel
            {
                User = user,
                Guest = guest
            };
            return View(viewModel);
        }
        else
        {
            var employee = await _employeeRepository.GetEmployeeByUserIDAsync(user.ID);
            if (employee == null)
            {
                return NotFound("Информации о сотруднике не найдено.");
            }
            var viewModel = new PersonalAccountViewModel
            {
                User = user,
                Employee = employee
            };
            return View(viewModel);
        }
    }

    [Route("PersonalAccount/UpdatePassword")]
    [HttpGet]
    public IActionResult UpdatePassword()
    {
        return View();
    }
    
    [Route("PersonalAccount/UpdatePassword")]
    [HttpPost]
    public async Task<IActionResult> UpdatePassword([FromForm]string newPassword)
    {
        var userId = User.FindFirst(ClaimTypes.NameIdentifier)?.Value;

        if (userId == null)
        {
            return Unauthorized();
        }

        if (string.IsNullOrWhiteSpace(newPassword))
        {
            ModelState.AddModelError(string.Empty, "Поле не должно быть пустым.");
            return View();
        }

        var userIdGuid = Guid.Parse(userId);
        var success = await _userRepository.UpdatePasswordAsync(userIdGuid, _authService.HashPassword(newPassword));

        if (!success)
        {
            ModelState.AddModelError(string.Empty, "Не удалось изменить пароль.");
            return View();
        }

        return RedirectToAction("PersonalAccount"); 
    }

    
    [Route("Logout")]
    [HttpGet]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return RedirectToAction("Login");
    }
    
    [Authorize(Roles = "Admin, PassOfficeEmployee")]
    [HttpGet("Details/{id}")]
    public async Task<IActionResult> Details(Guid id)
    {
        var user = await _userRepository.GetUserByIdAsync(id);
        if (user == null)
        {
            return NotFound();
        }
        return View(user);
    }
    
    [HttpPost("Update/{id}")]
    [Authorize(Roles = "Admin, PassOfficeEmployee")]
    public async Task<IActionResult> Update(Guid id, [FromForm] User user)
    {
        if (id != user.ID)
        {
            return BadRequest("Несоответствие идентификатора пользователя.");
        }

        if (!ModelState.IsValid)
        {
            return View("Details", user);
        }

        var existingUser = await _userRepository.GetUserByIdAsync(id);
        if (existingUser == null)
        {
            return NotFound();
        }

        existingUser.Role = user.Role;
        existingUser.Login = user.Login;
        existingUser.Password = user.Password;

        var updatedUser = await _userRepository.UpdateUserAsync(existingUser);
        if (updatedUser == null)
        {
            return StatusCode(500, "An error occurred while updating the user.");
        }

        return RedirectToAction("Details", new { id = user.ID });
    }

}

TheAccessSystemCourseWork/Views/Shared/AccessDenied.cshtml
@{
    ViewData["Title"] = "Доступ запрещён";
}

<h1>Доступ запрещён</h1>
<p>Доступ к запрашиваему ресурсу запрещён. Если вы считаете, что произошла ошибка, свяжитесь с администратором системы</p>

TheAccessSystemCourseWork/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Система пропусков</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/TheAccessSystemCourseWork.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            @if (User.Identity.IsAuthenticated)
            {
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="PersonalAccount">Система пропусков</a>
            }
            else
            {
                <a class="navbar-brand" asp-area="" asp-controller="User" asp-action="Login">Система пропусков</a>
            }
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.Identity.IsAuthenticated)
                    {
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Checkpoints">Контрольные точки</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="FactoryAreas">Помещения</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="UploadMap">Конструктор карты</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Rights" asp-action="List">Уровни прав</a>
                            </li>
                        }
                        @if (User.IsInRole("PassOfficeEmployee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassOfficeEmployee" asp-action="CreateUser">Регистрация пользователя</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassOfficeEmployee" asp-action="ViewPasses">Пропуска</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassOfficeEmployee" asp-action="ViewEmployees">Сотрудники</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="PassOfficeEmployee" asp-action="ViewGuests">Гости</a>
                            </li>
                        }
                        @if (User.IsInRole("SecurityServiceEmployee"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="SecurityServiceEmployee" asp-action="GetPassingAttempts">История проходов через КТ</a>
                            </li>

                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Map" asp-action="ViewBuildings">Просмотр карты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="PersonalAccount">Личный кабинет</a>
                        </li>
                        <li class="nav-item">
                            <form asp-area="" asp-controller="User" asp-action="Logout" method="post" class="form-inline">
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Logout">Выход</a>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Авторизация</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - Пропускная система - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>