TheAccessSystemCourseWork/Controllers/PassController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TheAccessSystemCourseWork.Models;
using TheAccessSystemCourseWork.Repositories.Interfaces;

namespace TheAccessSystemCourseWork.Controllers;

[ApiController]
[Route("{controller}")]
public class PassController : Controller
{
    private readonly IPassRepository _passRepository;
    private readonly IPassRightsRepository _passRightsRepository;
    private readonly IRightsLevelRepository _rightsLevelRepository;

    public PassController(IPassRepository passRepository,
                        IPassRightsRepository passRightsRepository,
                        IRightsLevelRepository rightsLevelRepository)
    {
        _passRepository = passRepository;
        _passRightsRepository = passRightsRepository;
        _rightsLevelRepository = rightsLevelRepository;
    }

    [HttpGet("Details/{id}")]
    public async Task<IActionResult> Details(Guid id)
    {
        try
        {
            var pass = await _passRepository.GetPassByIdAsync(id);
            var rightsLevels = await _rightsLevelRepository.FindRightsLevelsAsync();

            ViewBag.RightsLevels = rightsLevels;
            return View(pass);
        }
        catch (Exception ex)
        {
            return View("Error");
        }
    }

    [HttpPost("UpdatePass/{request}")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> UpdatePass([FromForm] UpdatePassRequest request)
    {
        try
        {
            var existingPass = await _passRepository.GetPassByIdAsync(request.Pass.ID);
            if (existingPass == null)
            {
                return NotFound("Pass not found.");
            }
    
            existingPass.IsAttached = request.Pass.IsAttached;
            existingPass.IsActive = request.Pass.IsActive;
            existingPass.ExpiredAt = request.Pass.ExpiredAt;
    
            existingPass.PassRights.Clear();
            foreach (var rightsId in request.RightsIds)
            {
                existingPass.PassRights.Add(new PassRights
                {
                    PassID = request.Pass.ID,
                    RightsLevelID = rightsId
                });
            }
    
            await _passRepository.UpdatePassAsync(existingPass);
            return RedirectToAction("Login", "User");
        }
        catch (Exception ex)
        {
            return View("Error");
        }
    }
    
    public class UpdatePassRequest
    {
        public Pass Pass { get; set; }
        public List<string> RightsIds { get; set; }
    }

}

TheAccessSystemCourseWork/Controllers/PassOfficeEmployeeController.cs
using System.Runtime.InteropServices.JavaScript;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TheAccessSystemCourseWork.Models;
using TheAccessSystemCourseWork.Repositories.Interfaces;
using TheAccessSystemCourseWork.Services;

namespace TheAccessSystemCourseWork.Controllers
{
    [ApiController]
    [Route("PassOfficeEmployee")]
    [Authorize(Roles = "PassOfficeEmployee, Admin")]
    public class PassOfficeEmployeeController : Controller
    {
        private readonly IPassRepository _passRepository;
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IPassRightsRepository _passRightsRepository;
        private readonly IUserRepository _userRepository;
        private readonly IPassOperationRepository _passOperationRepository;
        private readonly IRightsLevelRepository _rightsLevelRepository;
        private readonly IGuestRepository _guestRepository;
        private readonly AuthService _authService;

        public PassOfficeEmployeeController(IPassRepository passRepository,
                                            IEmployeeRepository employeeRepository,
                                            IPassRightsRepository passRightsRepository,
                                            IUserRepository userRepository,
                                            IPassOperationRepository passOperationRepository,
                                            IRightsLevelRepository rightsLevelRepository,
                                            IGuestRepository guestRepository,
                                            AuthService authService)
        {
            _passRepository = passRepository;
            _employeeRepository = employeeRepository;
            _passRightsRepository = passRightsRepository;
            _userRepository = userRepository;
            _passOperationRepository = passOperationRepository;
            _rightsLevelRepository = rightsLevelRepository;
            _guestRepository = guestRepository;
            _authService = authService;
        }

        [HttpGet("ViewEmployees")]
        public async Task<IActionResult> ViewEmployees(  
            int? serviceNumber = null,
            string? firstName = null,
            string? secondName = null,
            string? position = null,
            int? department = null,
            DateTime? birthDate = null)
        {
            try
            {
                var employees = await _employeeRepository.FindEmployeesAsync(
                    serviceNumber, 
                    firstName,
                    secondName,
                    position,
                    department,
                    birthDate);
                
                return View(employees);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Ошибка на сервере: {ex.Message}");
            }
        }
        
        [HttpGet("ViewGuests")]
        public async Task<IActionResult> ViewGuests(
            string? firstName = null,
            string? secondName = null,
            string? middleName = null,
            Int64? passport = null,
            string? phoneNumber = null)
        {
            var guests = await _guestRepository.FindGuestsAsync(firstName, secondName, middleName, passport, phoneNumber);
            return View(guests);
        }

        [HttpGet("CreateGuest")]
        public async Task<IActionResult> CreateGuest()
        {
            var users = await _userRepository.FindUsersAsync(Roles.Guest);
            var linkedUserIds = (await _employeeRepository.FindEmployeesAsync()).Select(e => e.UserID)
                .Concat((await _guestRepository.FindGuestsAsync()).Select(g => g.UserID)).ToList();
            var availableUsers = users.Where(u => !linkedUserIds.Contains(u.ID)).ToList();

            ViewBag.AvailableUsers = availableUsers;

            return View();
        }
        
        [HttpGet("EditGuest/{passport}")]
        public async Task<IActionResult> EditGuest(Int64 passport)
        {
            var guest = await _guestRepository.GetGuestByPassport(passport);
            if (guest == null)
            {
                return NotFound();
            }

            return View(guest);
        }

        [HttpPost("EditGuest/{passport}")]
        [Authorize(Roles = "Admin, PassOfficeEmployee")]
        public async Task<IActionResult> EditGuest(Int64 passport, [FromForm] Guest guest)
        {
            if (passport != guest.Passport)
            {
                return BadRequest("The passport number does not match the guest's passport number.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingGuest = await _guestRepository.GetGuestByPassport(passport);
                    if (existingGuest == null)
                    {
                        return NotFound();
                    }

                    existingGuest.FirstName = guest.FirstName;
                    existingGuest.SecondName = guest.SecondName;
                    existingGuest.MiddleName = guest.MiddleName;
                    existingGuest.PhoneNumber = guest.PhoneNumber;
                    existingGuest.UserID = guest.UserID;

                    var success = await _guestRepository.UpdateGuestAsync(existingGuest);
                    if (success)
                    {
                        return RedirectToAction("ViewGuests");
                    }

                    return StatusCode(500, "An error occurred while updating the guest.");
                }
                catch (Exception ex)
                {
                    return StatusCode(500, $"Server error: {ex.Message}");
                }
            }
    
            return View(guest);
        }

        [HttpPost("CreateGuest")]
        public async Task<IActionResult> CreateGuest([FromForm]Guest guest)
        {
            if (ModelState.IsValid)
            {
                await _guestRepository.CreateGuestAsync(guest);
                return RedirectToAction("ViewGuests");
            }

            return RedirectToAction("CreateGuest");
        }

        [HttpPost("EditEmployee")]
        [Authorize(Roles = "Admin, PassOfficeEmployee")]
        public async Task<IActionResult> UpdateEmployee([FromForm] Employee updatedEmployee)
        {
            try
            {
                var existingEmployee = await _employeeRepository.GetEmployeeByServiceNumber(updatedEmployee.ServiceNumber);
                if (existingEmployee == null)
                {
                    return NotFound();
                }

                existingEmployee.FirstName = updatedEmployee.FirstName;
                existingEmployee.SecondName = updatedEmployee.SecondName;
                existingEmployee.MiddleName = updatedEmployee.MiddleName;
                existingEmployee.Department = updatedEmployee.Department;
                existingEmployee.Position = updatedEmployee.Position;
                existingEmployee.BirthDate = updatedEmployee.BirthDate;
                existingEmployee.PhoneNumber = updatedEmployee.PhoneNumber;

                var success = await _employeeRepository.UpdateEmployeeAsync(existingEmployee);
                if (success)
                {
                    return RedirectToAction("ViewEmployees");
                }
                return NotFound();
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Ошибка на сервере: {ex.Message}");
            }
        }
        
        [HttpGet("EditEmployee/{serviceNumber}")]
        public async Task<IActionResult> EditEmployee(int serviceNumber)
        {
            try
            {
                var employee = await _employeeRepository.GetEmployeeByServiceNumber(serviceNumber);
                if (employee == null)
                {
                    return NotFound();
                }

                return View("EditEmployee", employee);
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Ошибка на сервере: {ex.Message}");
            }
        }
        
        [HttpGet("CreateEmployee")]
        public async Task<IActionResult> CreateEmployee()
        {
            var users = await _userRepository.FindUsersAsync();
            var linkedUserIds = (await _employeeRepository.FindEmployeesAsync()).Select(e => e.UserID)
                .Concat((await _guestRepository.FindGuestsAsync()).Select(g => g.UserID)).ToList();
            var availableUsers = users.Where(u => !linkedUserIds.Contains(u.ID)).ToList();
        
            ViewBag.AvailableUsers = availableUsers;
        
            return View();
        }

        [HttpPost("CreateEmployee")]
        public async Task<IActionResult> CreateEmployee([FromForm]Employee employee)
        {
            if (ModelState.IsValid)
            {
                await _employeeRepository.CreateEmployeeAsync(employee);
                return RedirectToAction("ViewEmployees");
            }

            return RedirectToAction("CreateEmployee");
        }

        [HttpPost("CreateUser")]
        public async Task<IActionResult> CreateUser([FromForm]User newUser)
        {
            try
            {
                var hashedPassword = _authService.HashPassword(newUser.Password);
                newUser.Password = hashedPassword;
                var success = await _userRepository.CreateUserAsync(newUser);
                if (success)
                {
                    return newUser.Role == Roles.Guest ? RedirectToAction("CreateGuest") : RedirectToAction("CreateEmployee");
                }
                return BadRequest();
            }
            catch (Exception ex)
            {
                return StatusCode(500, $"Ошибка на сервере: {ex.Message}");
            }

TheAccessSystemCourseWork/Views/PassOfficeEmployee/CreateEmployee.cshtml
@model TheAccessSystemCourseWork.Models.Employee

@{
    ViewBag.Title = "Создание сотрудника";
    Layout = "_Layout";
}

<h2>Создание сотрудника</h2>

<form asp-action="CreateEmployee" method="post">
    <div class="form-group">
        <label asp-for="UserID" class="control-label">Пользователь</label>
        <select asp-for="UserID" class="form-control">
            <option value="">Выберите пользователя</option>
            @foreach (var user in ViewBag.AvailableUsers)
            {
                <option value="@user.ID">@user.Login</option>
            }
        </select>
        <span asp-validation-for="UserID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия</label>
        <input asp-for="SecondName" class="form-control" />
        <span asp-validation-for="SecondName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MiddleName" class="control-label">Отчество</label>
        <input asp-for="MiddleName" class="form-control" />
        <span asp-validation-for="MiddleName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BirthDate" class="control-label">Дата рождения</label>
        <input asp-for="BirthDate" class="form-control" type="date" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Position" class="control-label">Должность</label>
        <input asp-for="Position" class="form-control" />
        <span asp-validation-for="Position" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Department" class="control-label">Подразделение</label>
        <input asp-for="Department" class="form-control" />
        <span asp-validation-for="Department" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона</label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Создать</button>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TheAccessSystemCourseWork/Views/PassOfficeEmployee/CreateGuest.cshtml
@model TheAccessSystemCourseWork.Models.Guest

@{
    ViewBag.Title = "Создание гостя";
    Layout = "_Layout";
}

<h2>Создание гостя</h2>

<form asp-action="CreateGuest" method="post">
    <div class="form-group">
        <label asp-for="UserID" class="control-label">Пользователь</label>
        <select asp-for="UserID" class="form-control">
            <option value="">Выберите пользователя</option>
            @foreach (var user in ViewBag.AvailableUsers)
            {
                <option value="@user.ID">@user.Login</option>
            }
        </select>
        <span asp-validation-for="UserID" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Passport" class="control-label">Паспортные данные</label>
        <input asp-for="Passport" class="form-control" />
        <span asp-validation-for="Passport" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя</label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия</label>
        <input asp-for="SecondName" class="form-control" />
        <span asp-validation-for="SecondName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MiddleName" class="control-label">Отчество</label>
        <input asp-for="MiddleName" class="form-control" />
        <span asp-validation-for="MiddleName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона</label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Создать</button>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TheAccessSystemCourseWork/Views/PassOfficeEmployee/CreatePass.cshtml
@model Pass

@{
    ViewBag.Title = "Регистрация пропуска";
    Layout = "_Layout";
    var rightsLevels = ViewBag.RightsLevels as List<RightsLevel>;
}

<h2>Регистрация пропуска</h2>

<div class="form-container">
    <div class="col-md-6">
        <form asp-action="CreatePass" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Type" class="control-label">Тип пропуска</label>
                <select asp-for="Type" class="form-control">
                    <option value="1">Одноразовый</option>
                    <option value="2">Временный</option>
                    <option value="3">Постоянный</option>
                </select>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="ExpiredAt" class="control-label">Дата истечения пропуска</label>
                <input asp-for="ExpiredAt" class="form-control"/>
                <span asp-validation-for="ExpiredAt" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Уровень прав</label>
                <div>
                    @foreach (var rightsLevel in rightsLevels)
                    {
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="rightsIds" value="@rightsLevel.ID" id="rights_@rightsLevel.ID" />
                            <label class="form-check-label" for="rights_@rightsLevel.ID">
                                @rightsLevel.Description
                            </label>
                        </div>
                    }
                </div>
            </div>

            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

TheAccessSystemCourseWork/Views/PassOfficeEmployee/CreateUser.cshtml
@model User

@{
    ViewBag.Title = "Зарегистрировать пользователя";
    Layout = "_Layout";
}

<h2>Регистрация пользователя</h2>

<div class="row">
    <div class="col-md-6">
        <form asp-action="CreateUser" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Login" class="control-label"></label>
                <input asp-for="Login" class="form-control" />
                <span asp-validation-for="Login" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Role" class="control-label"></label>
                <select asp-for="Role" class="form-control">
                    <option value="Employee">Сотрудник</option>
                    <option value="Guest">Гость</option>
                </select>
                <span asp-validation-for="Role" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PassID" class="control-label"></label>
                <select asp-for="PassID" class="form-control" asp-items="@ViewBag.PassList"></select>
                <span asp-validation-for="PassID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        function generateRandomString(length) {
            var result = '';
            var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!^&';
            var charactersLength = characters.length;
            for (var i = 0; i < length; i++) {
                result += characters.charAt(Math.floor(Math.random() * charactersLength));
            }
            return result;
        }

        $(document).ready(function () {
            var randomLogin = generateRandomString(8);
            var randomPassword = generateRandomString(12);
            $('#Login').val(randomLogin);
            $('#Password').val(randomPassword);
        });
    </script>
}

TheAccessSystemCourseWork/Views/PassOfficeEmployee/EditEmployee.cshtml
@model TheAccessSystemCourseWork.Models.Employee

@{
    ViewBag.Title = "Изменение данных сотрудника";
    bool canEdit = User.IsInRole("Admin") || User.IsInRole("PassOfficeEmployee");
    Layout = "_Layout";
}

<h2>Изменение данных сотрудника</h2>

<form method="post" asp-action="UpdateEmployee" asp-controller="PassOfficeEmployee">
    <input type="hidden" asp-for="ServiceNumber" />
    <input type="hidden" asp-for="BirthDate"/>

    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя:</label>
        @if (canEdit)
        {
            <input asp-for="FirstName" class="form-control" />
        }
        else
        {
            <input asp-for="FirstName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия:</label>
        @if (canEdit)
        {
            <input asp-for="SecondName" class="form-control" />
        }
        else
        {
            <input asp-for="SecondName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="MiddleName" class="control-label">Отчество:</label>
        @if (canEdit)
        {
            <input asp-for="MiddleName" class="form-control" />
        }
        else
        {
            <input asp-for="MiddleName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="Position" class="control-label">Должность:</label>
        @if (canEdit)
        {
            <input asp-for="Position" class="form-control" />
        }
        else
        {
            <input asp-for="Position" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="Department" class="control-label">Подразделение:</label>
        @if (canEdit)
        {
            <input asp-for="Department" class="form-control" />
        }
        else
        {
            <input asp-for="Department" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона:</label>
        @if (canEdit)
        {
            <input asp-for="PhoneNumber" class="form-control" />
        }
        else
        {
            <input asp-for="PhoneNumber" class="form-control" readonly />
        }
    </div>
    @if (canEdit)
    {
        <button type="submit" class="btn btn-primary">Изменить</button>
    }
</form>

TheAccessSystemCourseWork/Views/PassOfficeEmployee/EditGuest.cshtml
@model TheAccessSystemCourseWork.Models.Guest

@{
    ViewBag.Title = "Изменение данных гостя";
    bool canEdit = User.IsInRole("Admin") || User.IsInRole("PassOfficeEmployee");
    Layout = "_Layout";
}

<h2>Изменение данных гостя</h2>

<form asp-action="EditGuest" method="post" asp-route-passport="@Model.Passport">
    <input type="hidden" asp-for="UserID"/>
    
    <div class="form-group">
        <label asp-for="Passport" class="control-label">Паспортные данные:</label>
        <input asp-for="Passport" class="form-control" readonly/>
    </div>
    <div class="form-group">
        <label asp-for="FirstName" class="control-label">Имя:</label>
        @if (canEdit)
        {
            <input asp-for="FirstName" class="form-control" />
        }
        else
        {
            <input asp-for="FirstName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="SecondName" class="control-label">Фамилия:</label>
        @if (canEdit)
        {
            <input asp-for="SecondName" class="form-control" />
        }
        else
        {
            <input asp-for="SecondName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="MiddleName" class="control-label">Отчество:</label>
        @if (canEdit)
        {
            <input asp-for="MiddleName" class="form-control" />
        }
        else
        {
            <input asp-for="MiddleName" class="form-control" readonly />
        }
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber" class="control-label">Номер телефона:</label>
        @if (canEdit)
        {
            <input asp-for="PhoneNumber" class="form-control" />
        }
        else
        {
            <input asp-for="PhoneNumber" class="form-control" readonly />
        }
    </div>
    @if (canEdit)
    {
        <button type="submit" class="btn btn-primary">Изменить</button>
    }
</form>

TheAccessSystemCourseWork/Views/PassOfficeEmployee/ViewEmployees.cshtml
@model IEnumerable<Employee>

@{
    ViewBag.Title = "Просмотр сотрудников";
    Layout = "_Layout";
}

<h2>Просмотр сотрудников</h2>

<p>
    <a asp-action="CreateEmployee" class="btn btn-primary">Добавить сотрудника</a>
</p>

<div class="row mb-3">
    <div class="col-md-3">
        <label for="firstName">Имя:</label>
        <input type="text" class="form-control" id="firstName" name="firstName">
    </div>
    <div class="col-md-3">
        <label for="secondName">Фамилия:</label>
        <input type="text" class="form-control" id="secondName" name="secondName">
    </div>
    <div class="col-md-3">
        <label for="position">Должность:</label>
        <input type="text" class="form-control" id="position" name="position">
    </div>
    <div class="col-md-3">
        <label for="department">Поздразделение:</label>
        <input type="number" class="form-control" id="department" name="department">
    </div>
</div>

<div class="row mb-3">
    <div class="col-md-3">
        <label for="birthDate">Дата рождения:</label>
        <input type="date" class="form-control" id="birthDate" name="birthDate">
    </div>
    <div class="col-md-3">
        <button type="button" class="btn btn-primary" onclick="searchEmployees()">Поиск</button>
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>ФИО</th>
            <th>Табельный</th>
            <th>Подразделение</th>
            <th>Должность</th>
            <th>Дата рождения</th>
            <th>Номер телефона</th>
            <th>Пользователь</th>
            <th>Пропуск</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
    @if (Model != null)
    {
        @foreach (var employee in Model)
        {
            <tr>
                <td>@employee.SecondName @employee.FirstName @employee.MiddleName</td>
                <td>@employee.ServiceNumber</td>
                <td>@employee.Department</td>
                <td>@employee.Position</td>
                <td>@employee.BirthDate.ToShortDateString()</td>
                <td>@employee.PhoneNumber</td>
                <td>
                    @if (employee.User != null)
                    {
                        <a href="@Url.Action("Details", "User", new { id = employee.UserID })">@employee.User.Login</a>
                    }
                </td>
                <td>
                    @if (employee.User?.Pass != null)
                    {
                        <a href="@Url.Action("Details", "Pass", new { id = employee.User.PassID })">@employee.User.Pass.Type.GetDisplayName()</a>
                    }
                </td>
                <td><a href="@Url.Action("EditEmployee", "PassOfficeEmployee", new { serviceNumber = employee.ServiceNumber })" class="btn btn-primary"><i class="fas fa-pencil-alt"></i> Изменить</a></td>
            </tr>
        }
    }
    </tbody>
</table>

@section Scripts {
    <script>
        function searchEmployees() {
            var firstName = $('#firstName').val();
            var secondName = $('#secondName').val();
            var position = $('#position').val();
            var department = $('#department').val();
            var birthDate = $('#birthDate').val();

            var url = '/PassOfficeEmployee/ViewEmployees?firstName=' + firstName
                                                    + '&secondName=' + secondName
                                                    + '&position=' + position
                                                    + '&department=' + department
                                                    + '&birthDate=' + birthDate;

            window.location.href = url;
        }
    </script>
}